[package]
name = "rust_ftp_bck"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dialoguer = "0.11.0"
duckdb = { version = "1.2.0", features = ["bundled"] }
prettytable-rs = "0.10.0"
rand = "0.8.5"
